version: '2'
services:
    api:
        build: ofercompas_sa .
        ports:
            - "42777:42777"
        depends_on:
            - servidor_php
    servidor_php:
        image: servidor_php
        ports:
            - "42778:42778"


