#
# Autogenerated by Thrift Compiler (0.14.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
import logging
from .ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport
all_structs = []


class Iface(object):
    def guardarArchivo(self, imagen):
        """
        Parameters:
         - imagen

        """
        pass

    def obtenerArchivos(self, ruta):
        """
        Parameters:
         - ruta

        """
        pass

    def eliminarArchivo(self, ruta):
        """
        Parameters:
         - ruta

        """
        pass


class Client(Iface):
    def __init__(self, iprot, oprot=None):
        self._iprot = self._oprot = iprot
        if oprot is not None:
            self._oprot = oprot
        self._seqid = 0

    def guardarArchivo(self, imagen):
        """
        Parameters:
         - imagen

        """
        self.send_guardarArchivo(imagen)
        return self.recv_guardarArchivo()

    def send_guardarArchivo(self, imagen):
        self._oprot.writeMessageBegin('guardarArchivo', TMessageType.CALL, self._seqid)
        args = guardarArchivo_args()
        args.imagen = imagen
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_guardarArchivo(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = guardarArchivo_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        if result.excepcion is not None:
            raise result.excepcion
        raise TApplicationException(TApplicationException.MISSING_RESULT, "guardarArchivo failed: unknown result")

    def obtenerArchivos(self, ruta):
        """
        Parameters:
         - ruta

        """
        self.send_obtenerArchivos(ruta)
        return self.recv_obtenerArchivos()

    def send_obtenerArchivos(self, ruta):
        self._oprot.writeMessageBegin('obtenerArchivos', TMessageType.CALL, self._seqid)
        args = obtenerArchivos_args()
        args.ruta = ruta
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_obtenerArchivos(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = obtenerArchivos_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        if result.excepcion is not None:
            raise result.excepcion
        raise TApplicationException(TApplicationException.MISSING_RESULT, "obtenerArchivos failed: unknown result")

    def eliminarArchivo(self, ruta):
        """
        Parameters:
         - ruta

        """
        self.send_eliminarArchivo(ruta)
        return self.recv_eliminarArchivo()

    def send_eliminarArchivo(self, ruta):
        self._oprot.writeMessageBegin('eliminarArchivo', TMessageType.CALL, self._seqid)
        args = eliminarArchivo_args()
        args.ruta = ruta
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_eliminarArchivo(self):
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = eliminarArchivo_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        if result.excepcion is not None:
            raise result.excepcion
        raise TApplicationException(TApplicationException.MISSING_RESULT, "eliminarArchivo failed: unknown result")


class Processor(Iface, TProcessor):
    def __init__(self, handler):
        self._handler = handler
        self._processMap = {}
        self._processMap["guardarArchivo"] = Processor.process_guardarArchivo
        self._processMap["obtenerArchivos"] = Processor.process_obtenerArchivos
        self._processMap["eliminarArchivo"] = Processor.process_eliminarArchivo
        self._on_message_begin = None

    def on_message_begin(self, func):
        self._on_message_begin = func

    def process(self, iprot, oprot):
        (name, type, seqid) = iprot.readMessageBegin()
        if self._on_message_begin:
            self._on_message_begin(name, type, seqid)
        if name not in self._processMap:
            iprot.skip(TType.STRUCT)
            iprot.readMessageEnd()
            x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
            oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
            x.write(oprot)
            oprot.writeMessageEnd()
            oprot.trans.flush()
            return
        else:
            self._processMap[name](self, seqid, iprot, oprot)
        return True

    def process_guardarArchivo(self, seqid, iprot, oprot):
        args = guardarArchivo_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = guardarArchivo_result()
        try:
            result.success = self._handler.guardarArchivo(args.imagen)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except ExcepcionArchivo as excepcion:
            msg_type = TMessageType.REPLY
            result.excepcion = excepcion
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("guardarArchivo", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_obtenerArchivos(self, seqid, iprot, oprot):
        args = obtenerArchivos_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = obtenerArchivos_result()
        try:
            result.success = self._handler.obtenerArchivos(args.ruta)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except ExcepcionArchivo as excepcion:
            msg_type = TMessageType.REPLY
            result.excepcion = excepcion
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("obtenerArchivos", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_eliminarArchivo(self, seqid, iprot, oprot):
        args = eliminarArchivo_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = eliminarArchivo_result()
        try:
            result.success = self._handler.eliminarArchivo(args.ruta)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except ExcepcionArchivo as excepcion:
            msg_type = TMessageType.REPLY
            result.excepcion = excepcion
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("eliminarArchivo", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

# HELPER FUNCTIONS AND STRUCTURES


class guardarArchivo_args(object):
    """
    Attributes:
     - imagen

    """


    def __init__(self, imagen=None,):
        self.imagen = imagen

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.imagen = Imagen()
                    self.imagen.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('guardarArchivo_args')
        if self.imagen is not None:
            oprot.writeFieldBegin('imagen', TType.STRUCT, 1)
            self.imagen.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(guardarArchivo_args)
guardarArchivo_args.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'imagen', [Imagen, None], None, ),  # 1
)


class guardarArchivo_result(object):
    """
    Attributes:
     - success
     - excepcion

    """


    def __init__(self, success=None, excepcion=None,):
        self.success = success
        self.excepcion = excepcion

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.I32:
                    self.success = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.excepcion = ExcepcionArchivo.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('guardarArchivo_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.I32, 0)
            oprot.writeI32(self.success)
            oprot.writeFieldEnd()
        if self.excepcion is not None:
            oprot.writeFieldBegin('excepcion', TType.STRUCT, 1)
            self.excepcion.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(guardarArchivo_result)
guardarArchivo_result.thrift_spec = (
    (0, TType.I32, 'success', None, None, ),  # 0
    (1, TType.STRUCT, 'excepcion', [ExcepcionArchivo, None], None, ),  # 1
)


class obtenerArchivos_args(object):
    """
    Attributes:
     - ruta

    """


    def __init__(self, ruta=None,):
        self.ruta = ruta

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.ruta = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('obtenerArchivos_args')
        if self.ruta is not None:
            oprot.writeFieldBegin('ruta', TType.STRING, 1)
            oprot.writeString(self.ruta.encode('utf-8') if sys.version_info[0] == 2 else self.ruta)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(obtenerArchivos_args)
obtenerArchivos_args.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'ruta', 'UTF8', None, ),  # 1
)


class obtenerArchivos_result(object):
    """
    Attributes:
     - success
     - excepcion

    """


    def __init__(self, success=None, excepcion=None,):
        self.success = success
        self.excepcion = excepcion

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.LIST:
                    self.success = []
                    (_etype3, _size0) = iprot.readListBegin()
                    for _i4 in range(_size0):
                        _elem5 = iprot.readBinary()
                        self.success.append(_elem5)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.excepcion = ExcepcionArchivo.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('obtenerArchivos_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.LIST, 0)
            oprot.writeListBegin(TType.STRING, len(self.success))
            for iter6 in self.success:
                oprot.writeBinary(iter6)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.excepcion is not None:
            oprot.writeFieldBegin('excepcion', TType.STRUCT, 1)
            self.excepcion.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(obtenerArchivos_result)
obtenerArchivos_result.thrift_spec = (
    (0, TType.LIST, 'success', (TType.STRING, 'BINARY', False), None, ),  # 0
    (1, TType.STRUCT, 'excepcion', [ExcepcionArchivo, None], None, ),  # 1
)


class eliminarArchivo_args(object):
    """
    Attributes:
     - ruta

    """


    def __init__(self, ruta=None,):
        self.ruta = ruta

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.ruta = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('eliminarArchivo_args')
        if self.ruta is not None:
            oprot.writeFieldBegin('ruta', TType.STRING, 1)
            oprot.writeString(self.ruta.encode('utf-8') if sys.version_info[0] == 2 else self.ruta)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(eliminarArchivo_args)
eliminarArchivo_args.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'ruta', 'UTF8', None, ),  # 1
)


class eliminarArchivo_result(object):
    """
    Attributes:
     - success
     - excepcion

    """


    def __init__(self, success=None, excepcion=None,):
        self.success = success
        self.excepcion = excepcion

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 0:
                if ftype == TType.I32:
                    self.success = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 1:
                if ftype == TType.STRUCT:
                    self.excepcion = ExcepcionArchivo.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('eliminarArchivo_result')
        if self.success is not None:
            oprot.writeFieldBegin('success', TType.I32, 0)
            oprot.writeI32(self.success)
            oprot.writeFieldEnd()
        if self.excepcion is not None:
            oprot.writeFieldBegin('excepcion', TType.STRUCT, 1)
            self.excepcion.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(eliminarArchivo_result)
eliminarArchivo_result.thrift_spec = (
    (0, TType.I32, 'success', None, None, ),  # 0
    (1, TType.STRUCT, 'excepcion', [ExcepcionArchivo, None], None, ),  # 1
)
fix_spec(all_structs)
del all_structs
