name: "Build and Push"
on:
  pull_request:
    branches:
      - masterCANCELADAEMERGENCIA
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Coppy repository
        uses: actions/checkout@v2

      - name: Iniciar Sesion Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USER_NAME_GERARDO }}
          password: ${{ secrets.TOKEN_ACCESS }}

      - name: Configurar QEMU
        uses: docker/setup-qemu-action@v1

      - name: Configurar Build_X
        uses: docker/setup-buildx-action@v1

      - name: Construir con buildx
        run: |
          docker buildx build \
          --push \
          --tag amigosinformaticos/api_ofercompas:latest \
          --platform linux/arm/v6 .




